# Generated by Django 2.2.6 on 2020-03-22 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memesDatabase', '0002_auto_20200322_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedescriptions',
            name='imageId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memesDatabase.Images'),
        ),
        migrations.AlterField(
            model_name='textdescriptions',
            name='imageId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memesDatabase.Images'),
        ),
    ]
