# Generated by Django 2.2.6 on 2020-03-22 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memesDatabase', '0003_auto_20200322_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagedescriptions',
            old_name='imageId',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='textdescriptions',
            old_name='imageId',
            new_name='image',
        ),
    ]
