# Generated by Django 2.2.6 on 2020-03-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memesDatabase', '0005_auto_20200323_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedescriptions',
            name='word',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='textdescriptions',
            name='word',
            field=models.TextField(unique=True),
        ),
    ]
